import Header from "@/components/Header";
import "./globals.css";
import type { Metadata } from "next";
import { Rubik } from "next/font/google";
import Footer from "@/components/Footer";

const rubik = Rubik({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-rubik",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={rubik.variable}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
